### ISSUE TITLE
Leverage named HTTP statuses

### ISSUE THREAD

**Issue by jdhmtl** [wayfair-incubator/forker#19]
## Problem Statement

Numeric HTTP response codes can be difficult to remember, making code using them somewhat more difficult to read.

## Proposed Solution

Rather than use integer HTTP codes directly, use named constants in order to improve readability.

```typescript
if (response.status === HTTP_OK) {
  // stuff
}

if (error.status === HTTP_FORBIDDEN) {
  // stuff
}
```

reads easier than having to remember 200, 201, 403, etc.

**Comment by lelia** [comment]
Implemented by #38
