### ISSUE TITLE
Support other GitHub instance then the current one in the executing workflow

### ISSUE THREAD

**Issue by rajbos** [wayfair-incubator/forker#254]
## Problem Statement
We use this on action on GitHub Enterprise Server to fork actions on github.com. Since the action runs in the local context by default, we need to make some changes to support this.

## Proposed Solution

Add a parameter for the target instance url

## Alternatives Considered
- none

## Additional Context
We already use the action with these changes, so I will contribute them back here as well.

**Comment by rajbos** [comment]
Yes @lelia, it is.

**Comment by lelia** [comment]
> Yes @lelia, it is.

Great! I left [some feedback](https://github.com/wayfair-incubator/forker/pull/255#pullrequestreview-1671958187) on your PR back in October, happy to take another pass once you've had a chance to make updates!
